### ISSUE TITLE
Proguard?

### ISSUE THREAD

**Issue by goonerDroid** [jgilfelt/chuck#10]
Is there any proguard rules for release builds?

**Comment by jgilfelt** [comment]
[The rules](https://github.com/jgilfelt/chuck/blob/master/library/proguard-rules.pro#L18) should be automatically [configured by the library](https://github.com/jgilfelt/chuck/blob/master/library/build.gradle#L10). What issue are you seeing with proguard, specifically?

**Comment by goonerDroid** [comment]
[This rule](https://github.com/jgilfelt/chuck/blob/master/library/proguard-rules.pro#L18) worked for me.Thanks!
