### ISSUE TITLE
lower minSdkVersion

### ISSUE THREAD

**Issue by Jeff11** [jgilfelt/chuck#18]
Does this library rely on minSdk 16? Our project still uses minSdk 15.

**Comment by jgilfelt** [comment]
Yes, because I don't have the interest, time or patience to support anything earlier.

**Comment by Sloy** [comment]
For future reference, you can just ignore the library's minSdk by adding this to your manifest:

```xml
<uses-sdk tools:overrideLibrary="com.readystatesoftware.chuck"/>
```

It's mostly safe, because this is just a debug feature and in case it fails when running on sdk 15... not a big deal.
