### ISSUE TITLE
Can i change the core GSON to some other json Parser library

### ISSUE THREAD

**Issue by aldefy** [jgilfelt/chuck#22]
Hi , i use logan square as my primary json parsing library , this library is dependent on GSON , can i change this ?

**Comment by jgilfelt** [comment]
No. How exactly is the Gson dependency conflicting with your use of another library?

**Comment by aldefy** [comment]
Its just im trying to reduce the app size , ur library is super helpful , but GSON is just an additional dependencies im looking to avoid , but i guess i can use it as is
