### ISSUE TITLE
Update to Moshi

### ISSUE THREAD

**Issue by NightlyNexus** [jgilfelt/chuck#26]
Would you consider a PR that updated from Gson to [Moshi](https://github.com/square/moshi)?

**Comment by jgilfelt** [comment]
Sure, if I can be convinced it actually makes the project better. AFAIK, Gson is still in active development, is widely used, has a relatively modest method count, and works for the purposes of this project.

**Comment by hzsweers** [comment]
> Gson is still in active development

This isn't actually true, nor are the current maintainers even at Google. Moshi has 1/3 the binary size impact of Gson as well

**Comment by AlexisQapa** [comment]
Hi, i was wondering the same thing, my project use mochi so embedding chuck force me to use another son parsing lib. While this would be nice to move to moshi, I'm wondering if one could easy add an abstraction layer so ppl can use whatever json lib they want, the same way you allow to inject OkHttpClient. At some point KotlinX will have a production ready solution for JSON without reflection and ppl might move to this solution.
