### ISSUE TITLE
cannot find symbol import okhttp3.internal.Platform

### ISSUE THREAD

**Issue by joreilly** [jgilfelt/chuck#27]
Am getting following error below after adding following to build.gradle.  

```
    debugCompile 'com.readystatesoftware.chuck:library:1.0.4'
    releaseCompile 'com.readystatesoftware.chuck:library-no-op:1.0.4'

```

```
LoggingInterceptor.java:35: error: cannot find symbol
import okhttp3.internal.Platform;
                       ^
  symbol:   class Platform
  location: package okhttp3.internal
```

**Comment by bryanleesh** [comment]
Having the same issue.

**Comment by jgilfelt** [comment]
Assuming you've tried all the Gradle voodoo, like resyncing the project and cleaning the build, could you let me know what Gradle version you're using (specified by `classpath 'com.android.tools.build:gradle:x.x.x'` in your project's `build.gradle`) and specifically which gradle task the build fails at?

Do you have custom build types specified other than `debug` and `release`? 

Does it work if you add the compile dependency unqualified (e.g. `compile 'com.readystatesoftware.chuck:library:1.0.4'`)?

**Comment by bryanleesh** [comment]
@jgilfelt hey im still not able to build the project after adding this library.
Attached is the error I get. [http://imgur.com/a/1xHJL](error)

Build gradle im using, `classpath 'com.android.tools.build:gradle:2.3.0'`
I don't have any custom build aside from `debug` and `release`.

Tried unqualified dependency as well, not working.
