### ISSUE TITLE
Support for pretty json

### ISSUE THREAD

**Issue by JigneshPatel23** [jgilfelt/chuck#32]
Do we have support for pretty json?
If not yet do we have plan to add it?

**Comment by jgilfelt** [comment]
I use [Gson's `setPrettyPrinting` option](https://github.com/jgilfelt/chuck/blob/master/library/src/main/java/com/readystatesoftware/chuck/internal/support/JsonConvertor.java#L35) to format the JSON output. I don't have plans to add anything else at the moment.

**Comment by JigneshPatel23** [comment]
Thanks it will definitely work for our need.
