### ISSUE TITLE
Post the notifications only on phone

### ISSUE THREAD

**Issue by Marc1510** [jgilfelt/chuck#34]
When using an Android Wear device connected to the phone where the app is running, all Chuck notifications are mirrored on the watch. They do not anything on the Watch so I suggest adding setLocalOnly to the notification. 
This prevents a lot of unwanted notifications on the watch:
https://developer.android.com/reference/android/app/Notification.Builder.html#setLocalOnly(boolean)

**Comment by jgilfelt** [comment]
Thanks!
