### ISSUE TITLE
Archive logs

### ISSUE THREAD

**Issue by abredykhin** [jgilfelt/chuck#38]
My app just crashed due to bad response from server. But I couldn't capture what was wrong in the response because Chuck also disappeared from notification area. And I can't access logs from the previous session. 

Would be nice to be able to access data captured in the previous session (before app crash)

**Comment by jgilfelt** [comment]
> And I can't access logs from the previous session.

I don't understand why that would be the case. Unless you manually clear it, Chuck persists request data for one week by default, and you can set a different retention period with the [`retainDataFor` method](https://github.com/jgilfelt/chuck/blob/master/library/src/main/java/com/readystatesoftware/chuck/ChuckInterceptor.java#L123). I can't stop the notification from disappearing if your application process crashes, but you can always launch the UI directly via intent.

**Comment by abredykhin** [comment]
My bad, didn't realize that data is being stored
