### ISSUE TITLE
Is there any way to use with Volley?

### ISSUE THREAD

**Issue by yerenutku** [jgilfelt/chuck#5]
Hi, I was wondering is there any way to use with Volley?

**Comment by jgilfelt** [comment]
No, not directly. This project relies on OkHttp's Interceptor feature, so you would have to configure Volley's HttpStack to use OkHttp3. There are a few examples floating around to do that, [like this](https://gist.github.com/alashow/c96c09320899e4caa06b), but I haven't tried it myself.
