### ISSUE TITLE
JSON is not pretty print.

### ISSUE THREAD

**Issue by nitin3210** [jgilfelt/chuck#53]
JSON should be pretty print.
please add this line
String prettyJson = new JSONObject(bodyString).toString(2)
bodyText.setText(prettyJson)

**Comment by aurae** [comment]
The library uses Gson to format JSON content properly. Maybe your body's `Content-Type` isn't set to `application/json`?

**Comment by nitin3210** [comment]
Thanks aurae.
 Yes, Issue at the server side. and default it is set to the text/html. now we changed the Content-Type and now it works like a charm :).  big thanks to you :)
