### ISSUE TITLE
Implement notification channels

### ISSUE THREAD

**Issue by Marc1510** [jgilfelt/chuck#59]
When targetting Android O (API level 26) the notifications do not work because the Notification Channels are not implemented.
https://developer.android.com/preview/features/notification-channels.html

**Comment by jgilfelt** [comment]
Fixed in 1.1.0

**Comment by tpfaff** [comment]
Do you have a snapshot build available anywhere?

**Comment by memfis19** [comment]
Hi, sorry for disturbing, but how should it work? I updated to version 1.1.0 but still no notifications.
