### ISSUE TITLE
Could not expand ZIP

### ISSUE THREAD

**Issue by yerenutku** [jgilfelt/chuck#6]
Project not building when added `debugCompile 'com.readystatesoftware.chuck:library:1.0.0'`
in my dependencies.
Error log below:

```
> Error:Execution failed for task ':app:prepareComReadystatesoftwareChuckLibrary100Library'.
> > Could not expand ZIP '/Users/yutku/.gradle/caches/modules-2/files-2.1/com.readystatesoftware.chuck/library/1.0.0/9b35ca88dde54d309b52db9dccfc0a9486546eaa/library-1.0.0.aar'.
```
What have i tried?
Invalidate cache and restart.
Update gradle version and tools version.

**Comment by jgilfelt** [comment]
A quick Google search on that error suggests it is a file/directory permissions issue. Are you able to rename the .aar file to .zip and manually extract it to that directory?
